version: "3.7"

services: 
  focalboard-db:
    image: postgres:13.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "boards", "-U", "boardsuser" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd
      - POSTGRES_DB=boards
    volumes:
      - "/opt/postgresql/focalboard/data:/var/lib/postgresql/data"
    secrets:
      - db_user
      - db_passwd

  focalboard:
    build: 
      context: .
    depends_on:
      - "focalboard-db"
    container_name: focalboard
    ports:
      - 8000:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    user: focalboard
    command: /opt/focalboard/bin/focalboard-server
    volumes:
      - "./config.json:/opt/focalboard/config.json"

secrets:
  db_user:
    file: ./focal_db_user.txt
  db_passwd:
    file: ./focal_db_passwd.txt
